name: Get newest csv

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: 
      - main
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Download csv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cURL request
        run: |
          set -x
          CSV_URL=`curl -f -L https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers | grep -Eo "https?://(.*)\.csv"`
          curl -o sponsoring-firms.csv -z sponsoring-firms.csv $CSV_URL
          git add sponsoring-firms.csv
          sudo apt install python3-pip
          pip install --upgrade csvtotable
          export PATH=$PATH:~/.local/bin
          rm index.html
          csvtotable sponsoring-firms.csv index.html
          HTML=`curl -f -L https://raw.githubusercontent.com/ozkanpakdil/ozkanpakdil.github.io/master/_includes/google_analytics.html`
          sed -i 's/<\/body>/$HTML<\/body>/g' index.html
          git add index.html
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: csv adding back to repo [skip ci] another test
