name: Get newest csv

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: 
      - main
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Download csv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cURL request
        run: |
          set -x
          ls -ltr
          CSV_URL=`curl -f -L https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers | grep -Eo "https?://(.*)\.csv"`
          curl -o sponsoring-firms.csv $CSV_URL
          git add sponsoring-firms.csv
          sudo apt install python3-pip
          pip install --upgrade csvtotable
          export PATH=$PATH:~/.local/bin
          rm index.html
          csvtotable sponsoring-firms.csv index.html
          HTML=`curl -f -L https://raw.githubusercontent.com/ozkanpakdil/ozkanpakdil.github.io/master/_includes/google_analytics.html|tr '\n' ' '`
          LINK=`curl -f -L https://raw.githubusercontent.com/ozkanpakdil/uk-visa-sponsor/main/link.js`
          sed -i "s~<\/body>~$HTML$LINK<\/body>~g" index.html
          DATE=${date}
          sed -i "s~<caption>Table</caption>~<caption>Company list from $DATE</caption>~g" index.html
          git add index.html
          git status
          ls -ltr
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: csv adding back to repo [skip ci] another test
