name: Get newest csv

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: 
      - main
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Download csv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cURL request
        run: |
          set -x
          ls -ltr
          CSV_URL=`curl -f -L https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers | grep -Eo "https?://(.*)\.csv"`
          curl -o sponsoring-firms.csv $CSV_URL
          git add sponsoring-firms.csv
          sudo apt install python3-pip
          pip install --upgrade csvtotable
          export PATH=$PATH:~/.local/bin
          rm index.html
          csvtotable sponsoring-firms.csv index.html
          HTML=`curl -f -L https://raw.githubusercontent.com/ozkanpakdil/ozkanpakdil.github.io/master/_includes/google_analytics.html|tr '\n' ' '`
          sed -i "s~<\/body>~</style>$HTML~g" index.html
          sed -i "s~<\/html>~ ~g" index.html
          DATE=`date`
          
          HORZAD='<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7072273676024711" crossorigin="anonymous"><\/script> <!-- ukvisa --> <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-7072273676024711" data-ad-slot="6126939351" data-ad-format="auto" data-full-width-responsive="true"><\/ins> <script> (adsbygoogle = window.adsbygoogle || []).push({}); <\/script>'
          sed -i "s~<caption>Table</caption>~<caption>UK Visa Sponsor Company list from $DATE</caption>$HORZAD~g" index.html
          sed -i "s~<title>Table</title>~<title>UK Visa Sponsor Company list from $DATE</title>~g" index.html
          sed -i "s~</head>~<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7072273676024711" crossorigin="anonymous"></script></head>~g" index.html
          
          cat link.html >> index.html
          
          git add index.html
          git status
          ls -ltr
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: csv adding back to repo [skip ci] another test
