name: Get newest csv

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Download csv
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          CSV_URL=`curl -f -L https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers | grep -Eo "https?://(.*)\.csv"`
          curl -o sponsoring-firms.csv -z sponsoring-firms.csv $CSV_URL
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: csv adding back to repo [skip ci] another test
